/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package processing.standalonedemo;

public class App {
    public static void main(String[] args) {
        MyPApplet.main(MyPApplet.class.getName());
    }
}
